In [1]:
import pandas as pd

df = pd.read_csv('expMixDS_4iter.csv', sep=';')

In [2]:
df.describe()

,Exp. No.,Train DS Length,Test DS Length,Precision,Recall,F1Score,Accuracy
count,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,2.500000,1240.714286,1101.000000,93.820021,92.202978,92.993539,98.138061
std,1.128152,187.039492,1018.131408,5.120782,5.998988,5.510509,1.507448
min,1.000000,1038.000000,92.000000,84.796099,79.166667,82.380074,95.077145
25%,1.750000,1071.000000,92.000000,89.713100,86.737246,88.031192,96.820991
50%,2.500000,1170.000000,1101.000000,95.257972,93.108346,94.011955,98.676579
75%,3.250000,1434.000000,2110.000000,98.632443,97.995572,98.378464,99.531028
max,4.000000,1566.000000,2110.000000,99.078458,98.464299,98.723466,99.620037

In [3]:
df_new = df.query("`Test DataSet` == 'GS91'").groupby('Combination')

In [4]:
df_new.first()

,Exp. No.,Train DS Length,Test DataSet,Test DS Length,Precision,Recall,F1Score,Accuracy
Combination,,,,,,,,
T100:GS0,1,1038,GS91,92,90.045942,87.892377,88.956127,97.832201
T100:GS12,1,1170,GS91,92,91.908877,87.443946,89.620835,97.907663
T100:GS24,1,1302,GS91,92,91.729027,87.032885,89.319271,97.825341
T100:GS3,1,1071,GS91,92,89.406780,86.733931,88.050076,97.643548
T100:GS36,1,1434,GS91,92,89.964994,86.434978,88.164666,97.598957
T100:GS48,1,1566,GS91,92,92.460938,88.452915,90.412529,98.075736
T100:GS6,1,1104,GS91,92,89.540230,87.331839,88.422247,97.670989

In [5]:
# df_new.describe()

In [6]:
df_new['Precision'].describe()

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,4.0,88.568782,1.566534,86.958464,87.364616,88.635362,89.839528,90.045942
T100:GS12,4.0,90.343297,2.780083,86.455982,89.334481,91.101429,92.110245,92.714349
T100:GS24,4.0,89.724181,2.118005,86.732407,89.332249,90.217645,90.609577,91.729027
T100:GS3,4.0,88.544683,2.408144,85.008818,88.260401,89.375521,89.659803,90.418873
T100:GS36,4.0,88.832164,2.411902,85.286344,88.411847,89.709338,90.129655,90.623637
T100:GS48,4.0,88.236783,3.550908,84.796099,85.598063,87.845048,90.483768,92.460938
T100:GS6,4.0,88.808153,2.131906,86.165480,87.765493,88.919530,89.962190,91.228070

In [7]:
df_new['Recall'].describe()

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,4.0,86.221011,1.600714,84.050179,85.739938,86.470745,86.951818,87.892377
T100:GS12,4.0,86.955306,1.462372,85.771277,85.790937,86.620719,87.785087,88.808511
T100:GS24,4.0,86.467513,1.414188,84.441489,86.130534,86.863217,87.200196,87.702128
T100:GS3,4.0,86.121550,2.060956,83.244681,85.596116,86.556930,87.082363,88.127660
T100:GS36,4.0,86.266293,2.061836,83.466312,85.692811,86.586664,87.160146,88.425532
T100:GS48,4.0,85.682931,4.618203,79.166667,84.072581,87.080400,88.690750,89.404255
T100:GS6,4.0,87.398429,0.775715,86.783154,86.921852,87.149962,87.626538,88.510638

In [8]:
df_new['F1Score'].describe() ## T100:GS6

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,4.0,87.375704,1.457193,85.740402,86.407292,87.403144,88.371557,88.956127
T100:GS12,4.0,88.610065,2.004000,86.125478,87.512274,88.797687,89.895478,90.719409
T100:GS24,4.0,88.052187,1.276853,86.712973,87.097199,88.088252,89.043240,89.319271
T100:GS3,4.0,87.288587,1.364766,85.688889,86.434916,87.366833,88.220505,88.731791
T100:GS36,4.0,87.509579,1.635567,86.006219,86.268810,87.260503,88.501272,89.511092
T100:GS48,4.0,86.914037,3.779617,82.380074,84.532184,87.431772,89.813625,90.412529
T100:GS6,4.0,88.093170,1.417843,86.473214,87.339608,88.025326,88.778889,89.848812

In [34]:
df_new['Accuracy'].describe() ## T100:GS6

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,10.0,98.350898,0.501089,97.331978,98.171761,98.529033,98.650929,98.960692
T100:GS12,10.0,98.402552,0.442281,97.624190,98.151385,98.513971,98.777759,98.888660
T100:GS24,10.0,98.223914,0.476136,97.527737,97.730303,98.444823,98.588618,98.707846
T100:GS3,10.0,98.533329,0.441996,97.783001,98.221388,98.629193,98.870879,99.057277
T100:GS36,10.0,97.908221,0.536502,97.109643,97.374055,98.152059,98.293292,98.529910
T100:GS48,10.0,97.334837,0.584914,96.262001,96.916525,97.462967,97.773717,98.114726
T100:GS6,10.0,98.553904,0.394904,97.916402,98.257753,98.693945,98.885987,99.001852

In [10]:
df_new = df.query("`Combination` == 'T100:GS0'").query("`Test DataSet` == 'GS91'")
df_new.head()

,Exp. No.,Combination,Train DS Length,Test DataSet,Test DS Length,Precision,Recall,F1Score,Accuracy
1,1,T100:GS0,1038,GS91,92,90.045942,87.892377,88.956127,97.832201
3,2,T100:GS0,1038,GS91,92,87.500000,84.050179,85.740402,95.756405
5,3,T100:GS0,1038,GS91,92,86.958464,86.303191,86.629588,96.043705
7,4,T100:GS0,1038,GS91,92,89.770723,86.638298,88.176700,96.923996

In [11]:
df_new = df.query("`Combination` == 'T100:GS0'").query("`Test DataSet` == 'Test'")
df_new.head()

,Exp. No.,Combination,Train DS Length,Test DataSet,Test DS Length,Precision,Recall,F1Score,Accuracy
0,1,T100:GS0,1038,Test,2110,98.403018,97.575975,97.987752,99.426522
2,2,T100:GS0,1038,Test,2110,98.461410,97.352669,97.903900,99.403005
4,3,T100:GS0,1038,Test,2110,98.260660,97.935674,98.097898,99.484282
6,4,T100:GS0,1038,Test,2110,98.275955,97.970936,98.123209,99.454074