In [1]:
import pandas as pd

df = pd.read_csv('expMixDS.csv', sep=';')

In [2]:
df.describe()

,Exp. No.,Train DS Length,Test DS Length,Precision,Recall,F1Score,Accuracy
count,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000
mean,5.500000,1240.714286,1101.000000,96.369484,95.541373,95.950645,99.004443
std,2.882595,186.027548,1012.622992,3.353513,3.972526,3.644161,0.930860
min,1.000000,1038.000000,92.000000,87.363139,85.463378,86.573237,96.262001
25%,3.000000,1071.000000,92.000000,93.674150,92.354780,93.075511,98.275500
50%,5.500000,1170.000000,1101.000000,96.921989,96.444649,96.671871,99.187598
75%,8.000000,1434.000000,2110.000000,99.511858,99.293235,99.402177,99.852498
max,10.000000,1566.000000,2110.000000,99.666793,99.588287,99.606566,99.910732

In [28]:
df_new = df.query("`Test DataSet` == 'GS91'").groupby('Combination')

In [29]:
df_new.first()

,Exp. No.,Train DS Length,Test DataSet,Test DS Length,Precision,Recall,F1Score,Accuracy
Combination,,,,,,,,
T100:GS0,1,1038,GS91,92,94.810079,94.207773,94.507966,98.960692
T100:GS12,1,1170,GS91,92,95.393474,92.862481,94.110964,98.888660
T100:GS24,1,1302,GS91,92,95.005807,91.704036,93.325727,98.696577
T100:GS3,1,1071,GS91,92,95.838106,93.796712,94.806421,99.036153
T100:GS36,1,1434,GS91,92,93.655706,90.470852,92.035735,98.463333
T100:GS48,1,1566,GS91,92,89.335938,85.463378,87.356761,97.389724
T100:GS6,1,1104,GS91,92,95.135747,94.282511,94.707207,99.001852

In [19]:
# df_new.describe()

In [30]:
df_new['Precision'].describe()

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,10.0,93.842456,1.491970,91.359843,93.244955,94.320672,94.999618,95.425435
T100:GS12,10.0,93.759796,1.591852,91.306436,92.259158,94.757960,94.906067,95.393474
T100:GS24,10.0,93.545047,1.554141,91.014235,92.407707,93.859037,94.586798,95.442478
T100:GS3,10.0,94.424622,1.126736,93.014167,93.353849,94.541105,95.277953,95.970537
T100:GS36,10.0,92.368132,1.584787,89.961390,91.124966,92.316676,93.613149,94.637346
T100:GS48,10.0,90.642175,1.707560,87.363139,89.709338,90.513745,92.183239,92.545872
T100:GS6,10.0,94.599704,1.047234,93.124725,93.718930,94.714477,95.447004,96.014017

In [31]:
df_new['Recall'].describe()

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,10.0,92.499567,1.576491,89.816602,91.941747,92.715244,93.445274,94.530577
T100:GS12,10.0,92.938728,1.129766,90.572536,92.630514,93.060171,93.706942,94.433927
T100:GS24,10.0,92.026311,1.214197,89.496341,91.676009,91.837766,92.324599,93.828095
T100:GS3,10.0,93.328574,1.348680,90.916918,92.671986,93.297464,93.981093,95.391904
T100:GS36,10.0,90.692434,1.364618,88.334051,90.088755,90.693694,90.937740,92.881484
T100:GS48,10.0,88.479414,2.010706,85.463378,87.047375,88.714298,89.663340,91.669822
T100:GS6,10.0,93.273089,1.380239,90.959966,92.896695,93.291667,94.082696,95.262705

In [35]:
df_new['F1Score'].describe() ## T100:GS6

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,10.0,93.164725,1.485118,90.581650,92.700689,93.506365,94.193681,94.795940
T100:GS12,10.0,93.342657,1.184947,91.299631,92.788110,93.830090,94.102536,94.648956
T100:GS24,10.0,92.774815,1.205863,90.430622,92.043311,93.195457,93.523151,94.202623
T100:GS3,10.0,93.871862,1.178963,92.066260,93.110036,93.888476,94.781696,95.680346
T100:GS36,10.0,91.518148,1.313773,89.744150,90.432438,91.628384,92.294041,93.751194
T100:GS48,10.0,89.543203,1.746478,86.573237,88.431930,89.835675,90.758373,92.105764
T100:GS6,10.0,93.929041,1.108527,92.029617,93.244234,94.139688,94.686784,95.406513

In [34]:
df_new['Accuracy'].describe() ## T100:GS6

,count,mean,std,min,25%,50%,75%,max
Combination,,,,,,,,
T100:GS0,10.0,98.350898,0.501089,97.331978,98.171761,98.529033,98.650929,98.960692
T100:GS12,10.0,98.402552,0.442281,97.624190,98.151385,98.513971,98.777759,98.888660
T100:GS24,10.0,98.223914,0.476136,97.527737,97.730303,98.444823,98.588618,98.707846
T100:GS3,10.0,98.533329,0.441996,97.783001,98.221388,98.629193,98.870879,99.057277
T100:GS36,10.0,97.908221,0.536502,97.109643,97.374055,98.152059,98.293292,98.529910
T100:GS48,10.0,97.334837,0.584914,96.262001,96.916525,97.462967,97.773717,98.114726
T100:GS6,10.0,98.553904,0.394904,97.916402,98.257753,98.693945,98.885987,99.001852